title: Michelle Chan
description: >
  **My name is Michelle.**
  
  Welcome to my site.
copyright: Michelle Chan
sass:
  sass_dir: assets/sass
# url: http://localhost:4000

# Author details for the jekyll-seo-tag gem
author:
  name: Michelle Chan
  email: michelchan421@gmail.com
  twitter: # twitter username without the @ symbol

disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "#"
linkedin_username: "#"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "#"
feed_icon: rss
email: "michelchan421@gmail.com"